"""Native context generator orchestrator."""
import os
from pathlib import Path
from typing import List

from .content_transform import ContentTransformer
from .file_loader import FileLoader
from .models import ContextFile, ContextRenderInput, TransformOptions
from .xml_renderer import XmlContextRenderer


class NativeContextGenerator:
    """Orchestrates native context generation."""
    
    def __init__(self) -> None:
        self._loader = FileLoader()
        self._renderer = XmlContextRenderer()
        self._transformer = ContentTransformer()
    
    def generate_xml(
        self,
        execution_root: Path,
        include_patterns: List[str],
        verbose: bool = False,
        compress: bool = False
    ) -> str:
        """Generate XML context from include patterns."""
        if verbose:
            print(f"Loading files from {execution_root} with patterns: {include_patterns}")
        
        files = self._loader.load(execution_root, include_patterns)
        
        if verbose:
            print(f"Loaded {len(files)} files")
        
        # Apply compression if requested
        if compress:
            transform_opts = TransformOptions(compress=True)
            transformed_files = []
            for file in files:
                transformed_content = self._transformer.transform(
                    file.content, file.path, transform_opts
                )
                transformed_files.append(ContextFile(
                    path=file.path,
                    content=transformed_content
                ))
            files = transformed_files
        
        # Build directory tree string
        tree_string = self._build_tree_string(execution_root, files)
        
        # Build generation header
        generation_header = f"Generated by ai-context-manager from {len(files)} files"
        
        # Create render payload
        payload = ContextRenderInput(
            generation_header=generation_header,
            tree_string=tree_string,
            files=files
        )
        
        return self._renderer.render(payload)
    
    def _build_tree_string(self, execution_root: Path, files: List[ContextFile]) -> str:
        """Build a directory tree representation."""
        if not files:
            return "No files found"
        
        # Build directory structure
        dirs = set()
        for file in files:
            file_path = Path(file.path)
            parts = file_path.parts
            for i in range(len(parts)):
                dirs.add("/".join(parts[:i+1]) if parts[i] != file_path.name else file_path.name)
        
        # Sort directories for consistent output
        sorted_dirs = sorted(dirs)
        
        # Build tree string
        lines = [execution_root.name]
        for dir_path in sorted_dirs:
            if "/" in dir_path:
                indent = "  " * (dir_path.count("/") - 1)
                name = dir_path.split("/")[-1]
                lines.append(f"{indent}├── {name}/")
            else:
                lines.append(f"├── {dir_path}")
        
        # Add files
        for file in files:
            file_path = Path(file.path)
            if "/" in str(file_path):
                indent = "  " * (str(file_path).count("/") - 1)
                name = file_path.name
                lines.append(f"{indent}├── {name}")
            else:
                lines.append(f"├── {file_path.name}")
        
        return "\n".join(lines)
